  name: Build
  on:
    push:
      branches: [ main, master ]
    pull_request:
      branches: [ main, master ]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Install pnpm
          uses: pnpm/action-setup@v2.2.1
          with:
            version: "8.x"
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: "18.x"
            cache: 'pnpm'
        - name: Install dependencies
          run: pnpm install
        - name: Build the project
          run: pnpm app:build
